### ISSUE TITLE
Crash on H

### ISSUE THREAD

**Issue by C-Noob404** [helldivers2fixes/HellbombScript#94]
Hi,

I have the issue that the script just crashes when I go for H.
It runs on admin and worked before but now when it comes to scanning it crashes right before it scans the mainboard.
I also tried it with Win Defender off, but didnt help.

Any ideas?

**Comment by helldivers2fixes** [comment]
My guess is that you have an Intel CPU and that the CPU microcode scanning function crashes. On some motherboards (I know of at the latest one Gigabyte motherboard) that it crashes on. If it's not even showing the motherboard info, then you likely have corruption in your Windows install. If that is the case, run this:
`sc config winmgmt start= disabled
net stop winmgmt
Winmgmt /salvagerepository %windir%\System32\wbem
Winmgmt /resetrepository %windir%\System32\wbem
sc config winmgmt start= auto`

Otherwise, If you want, I can work with you and attempt to get a permanent fix for the community. If not, copy and paste into your favorite text editor that has line numbers, then delete lines 1085 and 1087 and then paste it into your Admin PowerShell/Terminal console

**Comment by lr619** [comment]
Hello, I'm having a similar issue but its crashing after displaying motherboard info. here is what I see when it happens
<img width="607" alt="image" src="https://github.com/user-attachments/assets/4c4592d3-cab3-4f84-b129-543d8157cfa4" />

**Comment by helldivers2fixes** [comment]
This should be resolved #97
