### ISSUE TITLE
Memory multi-channel detection issue is back and some other inconsistencies.

### ISSUE THREAD

**Issue by Cantejito** [helldivers2fixes/HellbombScript#95]
1.9.3.1 - 2.0.0.1 - copied script of 2.0.0.1
![Screenshot_1](https://github.com/user-attachments/assets/20fe8a07-e7c9-40b7-848c-27097956793e)

• .exe and script version don't show "??" anymore, but now they show a boxed "?".
![Screenshot_2](https://github.com/user-attachments/assets/bbb2335b-d170-4498-bb49-c52a01b0e4a5)

• Multi-channel memory detection seems broken, again.

• akamaihd.nt fails on .exe but succeeds in script version.

• IPv6 DNS testing doesn't report results.

• I'm not using a bluetooth headset. My PC have bluetooth but is disabled.
![Screenshot_3](https://github.com/user-attachments/assets/a6d152ae-deda-4108-89c0-507584505f5c)

**Comment by helldivers2fixes** [comment]
Hey there! Thank you for the detailed messages and screenshots!

>• .exe and script version don't show "??" anymore, but now they show a boxed "?".
Screenshot_2

This should be related to PowerShell/Terminal versions. With the latest PowerShell/Terminal/Windows OS, it should work properly.

> • Multi-channel memory detection seems broken, again.

The newer algorithm is more accurate, and can catch more single-channel memory issues. However, it (as the description says) is not perfect due to the limitations of PowerShell/my unwillingness to add dependencies. If you have four RAM slots and the RAM sticks are next to each other, then it is reporting accurately, and your RAM is in the wrong slots.

> • akamaihd.nt fails on .exe but succeeds in script version.

I see several other connection issues. My guess is that your connection issues can change, and that if you run the scripts multiple times, you (should) find that they all report passing/or failing of akaimai's CDN intermittently.

> • IPv6 DNS testing doesn't report results.

Yes, this isn't very clear, and I plan to improve the messaging.

> • I'm not using a bluetooth headset. My PC have bluetooth but is disabled.

This is working correctly. It's simply stating the current configuration of the BTAGS service. In your case it's disabled (off). That _is_ the correct configuration for HD2 if you have a Bluetooth headset. Just because you aren't using Bluetooth doesn't change this fact.
